---
- name: Install apache packages
  yum:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ httpd_install_from }}"

- name: chmod log dir
  file:
    path: /var/log/httpd`
    state: directory
    mode: "{{ var_log_httpd_permission | default('0755') }}"

- name: copy static index.html to httpd /var/www/html/index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644
  notify:
  - httpd started

- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify:
  - restart firewalld
